/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab02ed;

import Entidades.Libros;
import EntiedadesOrdenamiento.OrdenarFechaAntaRec;
import EntiedadesOrdenamiento.OrdenarFechaRecaAnt;
import EntiedadesOrdenamiento.OrdenarNomLibroAsc;
import EntiedadesOrdenamiento.OrdenarNomLibroDesc;
import EntiedadesOrdenamiento.OrdenarPorCantidadMay;
import EntiedadesOrdenamiento.OrdenarPorCantidadMen;
import EntiedadesOrdenamiento.OrdenarPorNombreAsc;
import EntiedadesOrdenamiento.OrdenarPorNombreDesc;
import Entidades.Usuario;
import java.io.File;
import java.io.PrintWriter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mario
 */
public class form extends javax.swing.JFrame {
    

    /**
     * Creates new form form
     */
    //Aquí creamos la lista de usuarios
    ArrayList<Usuario> lUs;
    //Aquí la lñista de los libros de cada usuario
    //ArrayList<Libros> lLibros;
    DefaultTableModel modeloUsers;
    DefaultTableModel modeloLibros;
    DateFormat formatoFecha;
    int total;
    int seleccionFila =0;
    
    public form() {
        initComponents();
        lUs = new ArrayList<>();
        modeloUsers= (DefaultTableModel) this.jTableUsers.getModel();
        modeloLibros= (DefaultTableModel) this.jTableLibros.getModel();
        formatoFecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        
        //Bloqueando los componentes de agregar libro
        this.txtLibro.setEnabled(false);
        this.btnAddLibros.setEnabled(false);
        this.txtBusqRes.setEnabled(false);
        this.txtLibro.setEnabled(false);
        this.checkBoxEspanyol.setEnabled(false);
        this.checkBoxIngles.setEnabled(false);
        
        //Agregar algunos datos
        this.lUs.add(new Usuario("ALANIS", "E-2021-ALANIS", "ESTUDIANTE", 2 ));
        this.lUs.add(new Usuario("MARIO", "E-2021-MARIO", "ESTUDIANTE", 0 ));
        this.lUs.add(new Usuario("CARLOS", "D-2012-CARLOS", "DOCENTE", 1 ));
        
        this.lUs.get(0).listaLibros.add(new Libros("EL LIBRO DE LA SELVA", "Español", new Date() ));
        this.lUs.get(0).listaLibros.add(new Libros("PROGRAMANDO CON JAVA", "Español/Inglés", new Date() ));
        this.lUs.get(2).listaLibros.add(new Libros("UBUNTU SERVER", "Inglés", new Date() ));
        
        this.mostrarUsuarios();
        this.totalizarLibros();
        
    }
    
    //Función para agregar los nombres de los usuarios en el textbox
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupRol = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rButtonEstudiante = new javax.swing.JRadioButton();
        rButtonDocente = new javax.swing.JRadioButton();
        btnAddUser = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtLibro = new javax.swing.JTextField();
        btnAddLibros = new javax.swing.JButton();
        barLibrosCant = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCantidadLibros = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        checkBoxIngles = new javax.swing.JCheckBox();
        checkBoxEspanyol = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtBusqRes = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxUsuarios = new javax.swing.JComboBox<>();
        btnVerTodos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxLibros = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLibros = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnExportar = new javax.swing.JButton();
        btnImportar = new javax.swing.JButton();
        btnExpHtml = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        jLabel1.setText("Libro - Préstamos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del usuario:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 12))); // NOI18N

        jLabel3.setText("Nombre:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel6.setText("Año de ingreso:");

        jLabel12.setText("Rol:");

        btnGroupRol.add(rButtonEstudiante);
        rButtonEstudiante.setText("Estudiante");

        btnGroupRol.add(rButtonDocente);
        rButtonDocente.setText("Docente");

        btnAddUser.setText("Agregar");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerListModel(new String[] {"2019", "2020", "2021", "2022", "2023"}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rButtonEstudiante)
                        .addGap(27, 27, 27)
                        .addComponent(rButtonDocente))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rButtonEstudiante)
                    .addComponent(rButtonDocente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddUser)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar libros:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 12))); // NOI18N

        jLabel8.setText("Libro:");

        btnAddLibros.setText("Agregar");
        btnAddLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLibrosActionPerformed(evt);
            }
        });

        barLibrosCant.setMaximum(10);

        jLabel4.setText("0");

        jLabel10.setText("10");
        jLabel10.setToolTipText("");

        lblCantidadLibros.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblCantidadLibros.setText("(Libros añadidos: 0/10)");

        jLabel13.setText("Idioma(s):");

        checkBoxIngles.setText("Inglés");

        checkBoxEspanyol.setText("Español");

        jLabel9.setText("Seleccione un usuario desde la tabla y luego");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel15.setText("escriba el nombre del libro que desea añadir. ");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtBusqRes.setEditable(false);

        jLabel17.setText("Usuario:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(lblCantidadLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAddLibros)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel13))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(checkBoxEspanyol)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(checkBoxIngles))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(barLibrosCant, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusqRes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtBusqRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(checkBoxIngles)
                    .addComponent(checkBoxEspanyol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddLibros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(lblCantidadLibros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barLibrosCant, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de usuarios:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 12))); // NOI18N

        jLabel7.setText("Buscar nombre:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Carnet", "Rol", "Cantidad libros"
            }
        ));
        jTableUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableUsers);

        jLabel11.setText("Ordenar por: ");

        jComboBoxUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Nombre (A~Z)", "Nombre (Z~A)", "Cantidad de libros (Mayor~Menor)", "Cantidad de libros (Menor~Mayor)" }));
        jComboBoxUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUsuariosActionPerformed(evt);
            }
        });

        btnVerTodos.setText("Ver todos");
        btnVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerTodos))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnVerTodos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de libros:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 12))); // NOI18N

        jLabel16.setText("Ordenar por: ");

        jComboBoxLibros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Nombre Libro (A~Z)", "Nombre Libro (Z~A)", "Fecha (Recientes-Antiguos)", "Fecha (Antiguos-Recientes)" }));
        jComboBoxLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLibrosActionPerformed(evt);
            }
        });

        jTableLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Libro", "Idioma", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(jTableLibros);

        jLabel2.setText("Elija un usuario para mostrar los libros correspondientes:");

        jLabel5.setText("Libros del usuario:");

        txtUsuario.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(28, 28, 28))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total de libros prestados:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 12))); // NOI18N

        lblTotal.setFont(new java.awt.Font("Segoe UI", 3, 75)); // NOI18N
        lblTotal.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(lblTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funciones CSV / HTML:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 12))); // NOI18N

        btnExportar.setText("Exportar CSV");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        btnImportar.setText("Importar CSV");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        btnExpHtml.setText("Exportar HTML");
        btnExpHtml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpHtmlActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        btnLimpiar.setText("Limpiar/Borrar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExpHtml, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnExportar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExpHtml)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(365, 365, 365))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        
        //RECORDAR VALIDAR LOS DATOS
        //Una vez ya esté lo de las listas, en cantidad de libros debe de salir la cantidad de cada cliente
        
        String tmpCarnet = "";
        
        if((rButtonEstudiante.isSelected() || rButtonDocente.isSelected()) && txtNombre.getText().length()!=0){
        
            if(rButtonEstudiante.isSelected()){
            tmpCarnet = "E-" + this.jSpinner1.getValue().toString() +"-"+ this.txtNombre.getText().trim().toUpperCase(); 
            this.lUs.add(new Usuario(this.txtNombre.getText().trim().toUpperCase(), tmpCarnet, "ESTUDIANTE", 0 ));
            }
            else{

                tmpCarnet = "D-" + this.jSpinner1.getValue().toString() +"-"+ this.txtNombre.getText().trim().toUpperCase(); 
                this.lUs.add(new Usuario(this.txtNombre.getText().trim().toUpperCase(), tmpCarnet, "DOCENTE", 0));
            }


            this.txtNombre.setText(" ");            
            this.btnGroupRol.clearSelection();
            
            this.mostrarUsuarios();
  
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnAddLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLibrosActionPerformed

            //Validación            
            if((this.checkBoxEspanyol.isSelected() || this.checkBoxIngles.isSelected())&&this.txtLibro.getText().length()!=0){
                int usuario = this.obtenerIndice();
             
                //AQUÍ ESTOY VALIDANDO DE QUE SE GUARDEN LO LIBROS POR EL NOMBRE Y NÚMERO DE LISTA
                //String NOMBRE = this.txtNombre.getText();
                //&& this.lUs.get(usuario).nombre.equals(NOMBRE)
                if (this.checkBoxEspanyol.isSelected() && this.checkBoxIngles.isSelected() ){
                   
                    this.lUs.get(usuario).listaLibros.add(
                        new Libros( this.txtLibro.getText().trim().toUpperCase(), "Español/Inglés", new Date() ));
                        this.libroIngresado();
                    
                }
                else if (this.checkBoxEspanyol.isSelected()){
                    this.lUs.get(usuario).listaLibros.add(
                        new Libros( this.txtLibro.getText().trim().toUpperCase(), "Español", new Date() ));
                    this.libroIngresado();

                }
                else if (this.checkBoxIngles.isSelected()){
                    this.lUs.get(usuario).listaLibros.add(
                        new Libros( this.txtLibro.getText().trim().toUpperCase(), "Inglés", new Date() ));
                    this.libroIngresado();

                }
                else{
                    JOptionPane.showMessageDialog(null, "Debe seleccionar al menos un idioma");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
         
    }//GEN-LAST:event_btnAddLibrosActionPerformed

    private void jTableUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsersMouseClicked
        // Aquí se hará el evento de agregar libros al cliente que se seleccione
//        seleccionFila =   this.jTableUsers.rowAtPoint(evt.getPoint());
        this.txtLibro.setEnabled(true);
        this.btnAddLibros.setEnabled(true);
        this.txtBusqRes.setEnabled(true);
        this.txtLibro.setEnabled(true);
        this.checkBoxEspanyol.setEnabled(true);
        this.checkBoxIngles.setEnabled(true);
        
        //int indice = this.jTableUsers.getSelectedRow();
        
        int indice = this.obtenerIndice();
        
        this.txtBusqRes.setText(this.lUs.get(indice).nombre);
        this.txtUsuario.setText(this.lUs.get(indice).nombre);

        this.cargarLibros();
        this.cargarBarra();
        
        
        
    }//GEN-LAST:event_jTableUsersMouseClicked

    //INTENTO DE OBTENER EL ÍNDICE DESDE EL ARRAY
    public int obtenerIndice(){
        String nombre = String.valueOf(this.jTableUsers.getValueAt(this.jTableUsers.getSelectedRow(),0));
        Boolean recorrer=true; 
        int cont=-1;
        
        while(recorrer)
        {
            cont++;
            if (this.lUs.get(cont).nombre.equals(nombre)) recorrer=false;
            
        }

        return cont;
    }
    
    
    
    
    
     private void mostrarUsuarios() {
        modeloUsers.setRowCount(0);
            for(int i=0; i<this.lUs.size(); i++)
            {
                String[] registroU = {this.lUs.get(i).nombre, this.lUs.get(i).carnet, this.lUs.get(i).rol, Integer.toString(this.lUs.get(i).cantLibros) };
                modeloUsers.addRow(registroU);
            }
    } 
        
     
    private void cargarLibros(){
        modeloLibros.setRowCount(0);
        int indiceUsuario = this.obtenerIndice();
        int cantLibros = this.lUs.get(indiceUsuario).listaLibros.size();
        
        
        for(int i=0; i<cantLibros; i++)
        {
            String[] lLibros = {this.lUs.get(indiceUsuario).listaLibros.get(i).nombrelibro, this.lUs.get(indiceUsuario).listaLibros.get(i).idioma,  formatoFecha.format(this.lUs.get(indiceUsuario).listaLibros.get(i).fecha)};
            modeloLibros.addRow(lLibros);
        }
        
        if(cantLibros==10){
            this.btnAddLibros.setEnabled(false);
        }
        this.cargarBarra();
    }
    
    private void libroIngresado(){
        int indiceUsuario = this.obtenerIndice();
        int subTotal = this.lUs.get(indiceUsuario).cantLibros;
        this.lUs.get(indiceUsuario).cantLibros = subTotal+1;
      
        this.txtLibro.setText("");
        this.checkBoxEspanyol.setSelected(false);
        this.checkBoxIngles.setSelected(false);
        this.cargarLibros();
        this.totalizarLibros();
        this.mostrarUsuarios();
        
        JOptionPane.showMessageDialog(null, "El registro se guardó correctamente en la lista de: "+ this.lUs.get(indiceUsuario).nombre, "Guardado", JOptionPane.INFORMATION_MESSAGE);
        this.lblCantidadLibros.setText("(Libros añadidos: 0/10)");
        this.barLibrosCant.setValue(0);
         this.txtBusqRes.setText(" ");
         //this.txtUsuario.setText(" ");
         //modeloLibros.setRowCount(0);
        
    }
    
    private void totalizarLibros(){
        int maxUsers = this.lUs.size();
        int total = 0;
        
        for(int i=0; i<maxUsers; i++){
            
                total+= this.lUs.get(i).cantLibros;
            
        }
        this.lblTotal.setText(String.valueOf(total));

    }
    
    private void cargarBarra(){
        int indiceUsuario = this.obtenerIndice();
        int cantidadLibros = this.lUs.get(indiceUsuario).listaLibros.size();
        this.barLibrosCant.setValue(cantidadLibros);
        this.lblCantidadLibros.setText("(Libros añadidos: "+ cantidadLibros +"/10)");      
    }
    

            
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.modeloUsers.setRowCount(0);
        this.modeloLibros.setRowCount(0);
        String clienteBusq= this.txtBuscar.getText().trim().toUpperCase();
        total=0;
        Boolean recorrer=true; 
        int cont=-1;
        
        while(recorrer)
        {
            cont++;
            if (this.lUs.get(cont).nombre.equals(clienteBusq)) recorrer=false;
            
        }
   
        
        String[] registro = { this.lUs.get(cont).nombre, this.lUs.get(cont).carnet, this.lUs.get(cont).rol, ""+this.lUs.get(cont).cantLibros};
        this.modeloUsers.addRow(registro);
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodosActionPerformed
        this.txtBuscar.setText("");
        this.mostrarUsuarios();

    }//GEN-LAST:event_btnVerTodosActionPerformed

    private void jComboBoxUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUsuariosActionPerformed
        // TODO add your handling code here:
        String opcion = (String)jComboBoxUsuarios.getSelectedItem();
        
        if(opcion.equals("Nombre (A~Z)"))
        {
            OrdenarPorNombreAsc oNas = new OrdenarPorNombreAsc();
            this.lUs.sort(oNas);
            this.mostrarUsuarios();
        }
        if(opcion.equals("Nombre (Z~A)"))
        {
            OrdenarPorNombreDesc oNdes = new OrdenarPorNombreDesc();
            this.lUs.sort(oNdes);
            this.mostrarUsuarios();
        }
        if(opcion.equals("Cantidad de libros (Menor~Mayor)"))
        {
            OrdenarPorCantidadMen oLmenamay = new OrdenarPorCantidadMen();
            this.lUs.sort(oLmenamay);
            this.mostrarUsuarios();
        }
        if(opcion.equals("Cantidad de libros (Mayor~Menor)"))
        {
            OrdenarPorCantidadMay oLmayamen = new OrdenarPorCantidadMay();
            this.lUs.sort(oLmayamen);
            this.mostrarUsuarios();
        }
    }//GEN-LAST:event_jComboBoxUsuariosActionPerformed

    private void jComboBoxLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLibrosActionPerformed
        // TODO add your handling code here:
        int indice = this.jTableUsers.getSelectedRow();
        this.txtUsuario.setText(this.lUs.get(indice).nombre);
        
        String opcion = (String)jComboBoxLibros.getSelectedItem();
        
        if(opcion.equals("Nombre Libro (A~Z)"))
        {
            OrdenarNomLibroAsc oNas = new OrdenarNomLibroAsc();
             this.lUs.get(indice).listaLibros.sort(oNas);
            this.cargarLibros();
        }
        if(opcion.equals("Nombre Libro (Z~A)"))
        {
            OrdenarNomLibroDesc oNdes = new OrdenarNomLibroDesc();
            this.lUs.get(indice).listaLibros.sort(oNdes);
            this.cargarLibros();
        }
        if(opcion.equals("Fecha (Antiguos-Recientes)"))
        {
            OrdenarFechaAntaRec oAnt = new OrdenarFechaAntaRec();
            this.lUs.get(indice).listaLibros.sort(oAnt);
            this.cargarLibros();
        }
        if(opcion.equals("Fecha (Recientes-Antiguos)"))
        {
            OrdenarFechaRecaAnt oRec = new OrdenarFechaRecaAnt();
            this.lUs.get(indice).listaLibros.sort(oRec);
            this.cargarLibros();
        }
        
        
    }//GEN-LAST:event_jComboBoxLibrosActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        PrintWriter pw = null;
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showSaveDialog(null);
        File selectedFile = null;
        if (result == JFileChooser.APPROVE_OPTION){
            selectedFile = fileChooser.getSelectedFile();
        }
        
        try
        {
            pw = new PrintWriter(new File(selectedFile.getAbsolutePath()));
            StringBuilder strLinea = new StringBuilder();
            
            for (int j=0; j<this.lUs.size();j++)
            {
                strLinea.append("+," + this.lUs.get(j).nombre + "," + this.lUs.get(j).carnet +"," +
                        this.lUs.get(j).rol+"," + Integer.toString(this.lUs.get(j).cantLibros)+"\n");
                
                if (this.lUs.get(j).cantLibros == 0)
                {
                    //strLinea.append("*"+"\n");
                }
                else
                {
                    for (int i=0; i<this.lUs.get(j).listaLibros.size(); i++)
                    {
                        strLinea.append("-,"+this.lUs.get(j).listaLibros.get(i).nombrelibro +","+
                        this.lUs.get(j).listaLibros.get(i).idioma+","+
                        formatoFecha.format(this.lUs.get(j).listaLibros.get(i).fecha)+"\n");  
                    }
//                    strLinea.append("*"+"\n");
                    
                }
                
//                for(int i=0; i<UsuTmp.get(j).listaLibros ==0; i++)
//                {
//                    
//                }
//                
//                strLinea.append("-"+UsuTmp.listaLibros.get(i).nombrelibro +" , "+
//                        UsuTmp.listaLibros.get(i).idioma+" , "+
//                        formatoFecha.format(UsuTmp.listaLibros.get(i).fecha)+"\n");                        
//                i++;
                
                
                //Exportar tambien junto con la lista de libros
//                for (i=0; i<this.lUs.size(); i++)
//                {
//                    strLinea.append(this.lUs.get(i).listaLibros.get(i).nombrelibro);
//                }
                
            }
            

            pw.write(strLinea.toString());
            pw.close();
            this.jTextArea1.setText("¡Hecho!");
        }
        catch(Exception e)
        {
            this.jTextArea1.setText("ERROR: " + e.toString());
            
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.lUs.clear();
        this.modeloUsers.setRowCount(0);
        this.modeloLibros.setRowCount(0);
        this.jTextArea1.setText("Se han borrado todos los registros");
        this.barLibrosCant.setValue(0);
        this.txtBusqRes.setText(" ");
        this.txtUsuario.setText(" ");
        this.lblTotal.setText(String.valueOf(total));
        this.txtLibro.setEnabled(false);
        this.btnAddLibros.setEnabled(false);
        this.txtBusqRes.setEnabled(false);
        this.txtLibro.setEnabled(false);
        this.checkBoxEspanyol.setEnabled(false);
        this.checkBoxIngles.setEnabled(false);
        
        
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnExpHtmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpHtmlActionPerformed
        PrintWriter pw = null;
        try
        {
            //Cambiar la ruta dependiendo de la compu xd
            pw = new PrintWriter(new File("C:\\Users\\mario\\Desktop\\Librería.html"));
   
            //ARMAR EL ARCHIVO HTML
            StringBuilder strLinea = new StringBuilder();
            strLinea.append("<html><body>"+"\n");
            
            strLinea.append("<h1>Préstamo de libros</h1>"+"\n");
            //Recorriendo cada usuario
            for (int j=0; j<this.lUs.size();j++)
            {
                strLinea.append("<h3>Usuario #" + (j+1) + "</h3>" + "\n");
                strLinea.append("<p><b>Usuario:</b> "+ this.lUs.get(j).nombre +"</p>" + "\n");
                strLinea.append("<p><b>Carnet:</b> "+ this.lUs.get(j).carnet +"</p>" + "\n");
                strLinea.append("<p><b>Rol:</b> "+ this.lUs.get(j).rol +"</p>" + "\n");
                strLinea.append("<p><b>Cantidad de libros prestados:</b> "+ this.lUs.get(j).cantLibros +"</p>" + "\n");
                
                if (this.lUs.get(j).cantLibros == 0)
                {
                    strLinea.append("<p> <em>Este usuario no ha prestado ningún libro </em></p>" + "\n");
                }
                else
                {
                    strLinea.append("<table border='2'><tr><td><b>Libro</td><td><b>Idioma</td><td><b>Fecha</td></tr>" + "\n");
                    for(int i=0; i<this.lUs.get(j).listaLibros.size(); i++)
                    {
                        strLinea.append("<tr>"+"\n");
                        //1 PROP
                        strLinea.append("<td>");
                        strLinea.append(lUs.get(j).listaLibros.get(i).nombrelibro);
                        strLinea.append("</td>"+"\n");
                        //2 PROP
                        strLinea.append("<td>");
                        strLinea.append(lUs.get(j).listaLibros.get(i).idioma);
                        strLinea.append("</td>"+"\n");
                        //3 PROP
                        strLinea.append("<td>");
                        strLinea.append( formatoFecha.format(this.lUs.get(j).listaLibros.get(i).fecha) );
                        strLinea.append("</td>"+"\n");

                        strLinea.append("</tr>"+"\n");
                    }
                    strLinea.append("</table>" + "\n");
                    
                    
                }
                strLinea.append("<p>*************************************</p>" + "\n");
            }

            strLinea.append("</body></html>" + "\n");
            pw.write(strLinea.toString());
            pw.close();
            this.jTextArea1.setText("Hecho!");
        }
        catch (Exception e)
        {
            this.jTextArea1.setText("Fallamos, jefe");
        }
    }//GEN-LAST:event_btnExpHtmlActionPerformed

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss"); 
        
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        File selectedFile= null;
        if (result == JFileChooser.APPROVE_OPTION)
        {
            selectedFile = fileChooser.getSelectedFile();
            this.jTextArea1.setText("Archivo seleccionado: ");
        }

        try
        {
            Scanner scan = new Scanner(new File(selectedFile.getAbsolutePath()));
//            scan.nextLine();
            int usuario = 0;
            while(scan.hasNextLine())
            {
                
                String sLinea = scan.nextLine();
                String[] aDatos = sLinea.split(",");
                
                if (aDatos[0].equals("+")){
                    Usuario uTemp = new Usuario(aDatos[1],aDatos[2], aDatos[3], Integer.parseInt(aDatos[4]));
                    this.lUs.add(uTemp);
                    usuario++;
                }
                else
                {
                    this.lUs.get(usuario-1).listaLibros.add(
                        new Libros( aDatos[1], aDatos[2], formato.parse(aDatos[3])));
                }
                //
                
            }
            this.jTextArea1.setText("¡Archivo CSV importado con éxito!");
            this.mostrarUsuarios();
            this.totalizarLibros();
        }
        catch(Exception e)
        {
            this.jTextArea1.setText(e.toString());
        }
    }//GEN-LAST:event_btnImportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barLibrosCant;
    private javax.swing.JButton btnAddLibros;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExpHtml;
    private javax.swing.JButton btnExportar;
    private javax.swing.ButtonGroup btnGroupRol;
    private javax.swing.JButton btnImportar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVerTodos;
    private javax.swing.JCheckBox checkBoxEspanyol;
    private javax.swing.JCheckBox checkBoxIngles;
    private javax.swing.JComboBox<String> jComboBoxLibros;
    private javax.swing.JComboBox<String> jComboBoxUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTableLibros;
    private javax.swing.JTable jTableUsers;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCantidadLibros;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rButtonDocente;
    private javax.swing.JRadioButton rButtonEstudiante;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBusqRes;
    private javax.swing.JTextField txtLibro;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

   
}
